export const GET_ALL_DELIVERIES = 'GET_ALL_DELIVERIES';
export const GET_DELIVERY_BY_ID = 'GET_DELIVERY_BY_ID';
export const ADD_DELIVERY = 'ADD_DELIVERY';
export const UPDATE_DELIVERY_BY_ID = 'UPDATE_DELIVERY_BY_ID';
export const DELETE_DELIVERY_BY_ID = 'DELETE_DELIVERY_BY_ID';